/**
 * Seed script — inserts the 12 starter listings into Supabase.
 * Run: node server/supabase/seed.js
 *
 * Requires SUPABASE_URL and SUPABASE_SERVICE_ROLE_KEY in env.
 */
import 'dotenv/config'
import supabase from './client.js'

const PROPERTIES = [
  {
    name: 'The Canopy Residence',
    type: 'Detached Duplex',
    price: 850000000,
    address: '14 Ribadu Road, Ikoyi, Lagos',
    coords: [3.4333, 6.4542],
    beds: 5,
    baths: 6,
    area: 640,
    year_built: 2022,
    image: '/images/properties/property-1.jpg',
    images: ['/images/properties/property-1.jpg'],
    tagline: 'A five-bedroom statement home under a canopy of mature trees on quiet Ribadu Road.',
    description: 'Behind a gated forecourt on Ribadu Road, The Canopy Residence pairs double-height living spaces with a wrap-around veranda that overlooks a landscaped garden.',
    features: ['Double-height living room', 'Gourmet kitchen', 'Smart-home automation', 'Swimming pool', 'Staff quarters', 'Triple car garage', 'Solar-ready rooftop', '24/7 security'],
    agent: { name: 'Adaeze Okafor', role: 'Senior Sales Partner', phone: '+234 803 555 0142', email: 'adaeze.okafor@verdantestates.ng' },
  },
  {
    name: 'Lagoon Pearl Villa',
    type: 'Waterfront Villa',
    price: 1950000000,
    address: '7 Water Corporation Road, Banana Island, Lagos',
    coords: [3.426, 6.443],
    beds: 6,
    baths: 7,
    area: 980,
    year_built: 2021,
    image: '/images/properties/property-2.jpg',
    images: ['/images/properties/property-2.jpg'],
    tagline: 'A six-bedroom waterfront villa with private jetty and lagoon-facing infinity pool.',
    description: 'Lagoon Pearl Villa commands 180 degrees of the Lagos lagoon from Banana Islands exclusive eastern arm.',
    features: ['Private jetty', 'Infinity pool', 'Central courtyard', 'Cinema and gym', 'Six ensuite bedrooms', '24/7 security', 'Triple generators', 'Native palms'],
    agent: { name: 'Tunde Bakare', role: 'Private Office Director', phone: '+234 802 444 0198', email: 'tunde.bakare@verdantestates.ng' },
  },
  {
    name: 'Jasmine Court',
    type: 'Terrace Duplex',
    price: 520000000,
    address: '3 Admiralty Way, Lekki Phase 1, Lagos',
    coords: [3.48, 6.445],
    beds: 4,
    baths: 5,
    area: 420,
    year_built: 2023,
    image: '/images/properties/property-3.jpg',
    images: ['/images/properties/property-3.jpg'],
    tagline: 'A four-bedroom terrace duplex wrapped in jasmine and set minutes from the beach.',
    description: 'Jasmine Court sits on a leafy, gated close off Admiralty Way, steps from the Atlantic shoreline.',
    features: ['Gated close', 'Open-plan kitchen', 'Guest suite', 'Planted balconies', 'Near beach', 'Borehole water', 'Solar-assisted power', 'Estate management'],
    agent: { name: 'Chioma Eze', role: 'Sales Partner', phone: '+234 809 222 1076', email: 'chioma.eze@verdantestates.ng' },
  },
  {
    name: 'Palm Boulevard Penthouse',
    type: 'Penthouse',
    price: 780000000,
    address: 'Bishop Oluwole Street, Victoria Island, Lagos',
    coords: [3.424, 6.428],
    beds: 4,
    baths: 4,
    area: 380,
    year_built: 2022,
    image: '/images/properties/property-4.jpg',
    images: ['/images/properties/property-4.jpg'],
    tagline: 'A full-floor penthouse above Victoria Island with a wraparound sky terrace.',
    description: 'Occupying the entire 18th floor of a boutique tower on Victoria Island.',
    features: ['Full-floor footprint', 'Wraparound terrace', 'Chef kitchen', 'Walk-in dressing rooms', 'Residents gym', 'Four parking bays', 'Fibre internet', 'Prime location'],
    agent: { name: 'Femi Adeyemi', role: 'Luxury Resale Manager', phone: '+234 805 111 0834', email: 'femi.adeyemi@verdantestates.ng' },
  },
  {
    name: 'Fern House',
    type: 'Semi-Detached Duplex',
    price: 460000000,
    address: '26 Ademola Adetokunbo Street, Oniru, Lagos',
    coords: [3.469, 6.438],
    beds: 4,
    baths: 4,
    area: 360,
    year_built: 2020,
    image: '/images/properties/property-5.jpg',
    images: ['/images/properties/property-5.jpg'],
    tagline: 'A light-filled semi-detached duplex in Oniru with a fern-lined courtyard.',
    description: 'Fern House is built around a sunken courtyard that draws light and air deep into the plan.',
    features: ['Sunken courtyard', 'Green wall', 'Near Landmark Beach', 'Study nook', 'Ensuite bedrooms', 'CCTV security', 'Inverter system', 'Native landscaping'],
    agent: { name: 'Ngozi Obi', role: 'Sales Partner', phone: '+234 806 666 0912', email: 'ngozi.obi@verdantestates.ng' },
  },
  {
    name: 'Cedar Villa',
    type: 'Detached Villa',
    price: 690000000,
    address: '12 Chevron Drive, Lekki, Lagos',
    coords: [3.51, 6.441],
    beds: 5,
    baths: 6,
    area: 560,
    year_built: 2021,
    image: '/images/properties/property-6.jpg',
    images: ['/images/properties/property-6.jpg'],
    tagline: 'A five-bedroom villa off Chevron Drive with cedar ceilings and a forest garden.',
    description: 'Cedar Villas timber-lined ceilings and exposed stone walls give it the warmth of a mountain lodge.',
    features: ['Cedar ceilings', 'Forest garden', 'Covered lanai', 'Dual master suites', 'Media room', 'Guest house', 'Borehole and solar', 'Gated cul-de-sac'],
    agent: { name: 'Ibrahim Suleiman', role: 'Sales Partner', phone: '+234 807 777 0621', email: 'ibrahim.suleiman@verdantestates.ng' },
  },
  {
    name: 'Osborne Sky Residence',
    type: 'Apartment',
    price: 410000000,
    address: 'Osborne Foreshore, Ikoyi, Lagos',
    coords: [3.418, 6.447],
    beds: 3,
    baths: 4,
    area: 250,
    year_built: 2023,
    image: '/images/properties/property-7.jpg',
    images: ['/images/properties/property-7.jpg'],
    tagline: 'A three-bedroom residence on Osborne Foreshore with lagoon views from every room.',
    description: 'Set along the Osborne Foreshore promenade, this three-bedroom residence offers rare water views.',
    features: ['Lagoon-facing balcony', 'Open-plan living', 'Corner water views', 'Residents pool', '24-hour concierge', 'Two parking bays', 'Backup power', 'Near Ikoyi Club'],
    agent: { name: 'Adaeze Okafor', role: 'Senior Sales Partner', phone: '+234 803 555 0142', email: 'adaeze.okafor@verdantestates.ng' },
  },
  {
    name: 'Canopy Loft',
    type: 'Duplex Apartment',
    price: 185000000,
    address: '9 Herbert Macaulay Way, Yaba, Lagos',
    coords: [3.396, 6.517],
    beds: 3,
    baths: 3,
    area: 210,
    year_built: 2022,
    image: '/images/properties/property-8.jpg',
    images: ['/images/properties/property-8.jpg'],
    tagline: 'A designer duplex loft in Yabas creative quarter, minutes from the train line.',
    description: 'Canopy Loft brings gallery-style living to Yaba, with a double-height living volume.',
    features: ['Double-height living', 'Exposed concrete', 'Roof terrace', 'Near Blue Line', 'Bike store', 'Co-working lounge', 'Fibre broadband', 'Solar-assisted power'],
    agent: { name: 'Chioma Eze', role: 'Sales Partner', phone: '+234 809 222 1076', email: 'chioma.eze@verdantestates.ng' },
  },
  {
    name: 'Veranda House',
    type: 'Townhouse',
    price: 240000000,
    address: '18 Adeniran Ogunsanya, Surulere, Lagos',
    coords: [3.362, 6.503],
    beds: 3,
    baths: 3,
    area: 240,
    year_built: 2019,
    image: '/images/properties/property-9.jpg',
    images: ['/images/properties/property-9.jpg'],
    tagline: 'A classic Surulere townhouse with a deep veranda and a courtyard garden.',
    description: 'Veranda House honours Suruleres genteel past with deep verandas, timber louvers and a courtyard garden.',
    features: ['Deep veranda', 'Courtyard garden', 'Modern kitchen', 'Renovated ensuites', 'Carport', 'Central location', 'Inverter system', 'Tree-lined street'],
    agent: { name: 'Femi Adeyemi', role: 'Luxury Resale Manager', phone: '+234 805 111 0834', email: 'femi.adeyemi@verdantestates.ng' },
  },
  {
    name: 'Moss & Stone House',
    type: 'Detached Bungalow',
    price: 350000000,
    address: '5 Addo Road, Ajah, Lagos',
    coords: [3.556, 6.465],
    beds: 4,
    baths: 5,
    area: 330,
    year_built: 2021,
    image: '/images/properties/property-10.jpg',
    images: ['/images/properties/property-10.jpg'],
    tagline: 'A single-storey retreat in Ajah where moss walls meet stone floors.',
    description: 'Moss & Stone House is a modern bungalow designed for single-level living.',
    features: ['Single-level plan', 'Shaded veranda', 'Green wall', 'Wide doorways', 'Central lawn', 'Scullery', 'Borehole and power', 'Gated compound'],
    agent: { name: 'Ngozi Obi', role: 'Sales Partner', phone: '+234 806 666 0912', email: 'ngozi.obi@verdantestates.ng' },
  },
  {
    name: 'Garden Terrace',
    type: 'Terrace Duplex',
    price: 290000000,
    address: '3 Sasegbon Street, Ilupeju, Lagos',
    coords: [3.352, 6.532],
    beds: 4,
    baths: 4,
    area: 280,
    year_built: 2020,
    image: '/images/properties/property-11.jpg',
    images: ['/images/properties/property-11.jpg'],
    tagline: 'A four-bedroom terrace duplex on a leafy Ilupeju street near the golf course.',
    description: 'Garden Terrace lines a quiet, tree-shaded street in Ilupeju.',
    features: ['Rooftop terrace', 'Family kitchen', 'Near golf course', 'Ensuite bedrooms', 'Service quarters', 'Gated street', 'Backup power', 'Managed estate'],
    agent: { name: 'Ibrahim Suleiman', role: 'Sales Partner', phone: '+234 807 777 0621', email: 'ibrahim.suleiman@verdantestates.ng' },
  },
  {
    name: 'Atlantic View Apartment',
    type: 'Apartment',
    price: 320000000,
    address: 'Eko Atlantic, Victoria Island, Lagos',
    coords: [3.413, 6.418],
    beds: 2,
    baths: 2,
    area: 160,
    year_built: 2023,
    image: '/images/properties/property-12.jpg',
    images: ['/images/properties/property-12.jpg'],
    tagline: 'A two-bedroom apartment on the Eko Atlantic waterfront with ocean-facing balcony.',
    description: 'Steps from the Atlantic Ocean and the Eko Atlantic promenade.',
    features: ['Ocean-facing balcony', 'Floor-to-ceiling glazing', 'Stone counters', 'Estate parks', '24-hour security', 'Two parking bays', 'District cooling', 'Flood-protected'],
    agent: { name: 'Tunde Bakare', role: 'Private Office Director', phone: '+234 802 444 0198', email: 'tunde.bakare@verdantestates.ng' },
  },
]

async function seed() {
  console.log('Seeding listings into Supabase...')

  // Clear existing data
  await supabase.from('listings').delete().neq('id', 0)

  // Insert all properties
  const { data, error } = await supabase.from('listings').insert(PROPERTIES).select()

  if (error) {
    console.error('Seed failed:', error)
    process.exit(1)
  }

  console.log(`Seeded ${data.length} listings successfully!`)
  process.exit(0)
}

seed()
