// Seed script — imports the static properties from the frontend data
// and writes them into the server's JSON database.
// Run: npm run seed (from the server directory)

import { writeFileSync, existsSync } from 'node:fs'
import { join, dirname } from 'node:path'
import { fileURLToPath } from 'node:url'

const __dirname = dirname(fileURLToPath(import.meta.url))
const dataDir = join(__dirname, '..', 'data')

// Mirror of the properties from src/data/properties.js
const PROPERTIES = [
  {
    id: 1,
    name: 'The Canopy Residence',
    type: 'Detached Duplex',
    price: 850000000,
    address: '14 Ribadu Road, Ikoyi, Lagos',
    beds: 5,
    baths: 6,
    area: 640,
    yearBuilt: 2022,
    image: '/images/properties/property-1.jpg',
    tagline: 'A five-bedroom statement home under a canopy of mature trees on quiet Ribadu Road.',
    description: 'Behind a gated forecourt on Ribadu Road, The Canopy Residence pairs double-height living spaces with a wrap-around veranda that overlooks a landscaped garden. Floor-to-ceiling glazing pulls natural light through every floor, while the top-floor study opens onto a private terrace with skyline views across Ikoyi.',
    features: [
      'Double-height living room with glazed walls',
      'Gourmet kitchen with island and butler\'s pantry',
      'Smart-home automation throughout',
      'Private study with skyline terrace',
      'Swimming pool and outdoor entertaining deck',
      'Staff quarters and triple car garage',
      'Solar-ready rooftop with 15kW capacity',
      '24/7 security with backup power',
    ],
    agent: {
      name: 'Adaeze Okafor',
      role: 'Senior Sales Partner',
      phone: '+234 803 555 0142',
      email: 'adaeze.okafor@verdantestates.ng',
    },
  },
  {
    id: 2,
    name: 'Lagoon Pearl Villa',
    type: 'Waterfront Villa',
    price: 1950000000,
    address: '7 Water Corporation Road, Banana Island, Lagos',
    beds: 6,
    baths: 7,
    area: 980,
    yearBuilt: 2021,
    image: '/images/properties/property-2.jpg',
    tagline: 'A six-bedroom waterfront villa with private jetty and lagoon-facing infinity pool.',
    description: 'Lagoon Pearl Villa commands 180 degrees of the Lagos lagoon from Banana Island\'s exclusive eastern arm. The home is organised around a central courtyard that cools every room naturally, with an infinity pool spilling toward the water and a private jetty for boats. Marble, iroko timber and bronze detailing carry the interiors.',
    features: [
      'Private jetty and boat house',
      'Lagoon-facing infinity pool',
      'Central courtyard with rain garden',
      'Cinema, gym and wine cellar',
      'Six ensuite bedrooms, all lagoon-facing',
      'Smart security with 24/7 guardhouse',
      'Triple standby generators and solar hybrid',
      'Landscaped compound with native palms',
    ],
    agent: {
      name: 'Tunde Bakare',
      role: 'Private Office Director',
      phone: '+234 802 444 0198',
      email: 'tunde.bakare@verdantestates.ng',
    },
  },
  {
    id: 3,
    name: 'Jasmine Court',
    type: 'Terrace Duplex',
    price: 520000000,
    address: '3 Admiralty Way, Lekki Phase 1, Lagos',
    beds: 4,
    baths: 5,
    area: 420,
    yearBuilt: 2023,
    image: '/images/properties/property-3.jpg',
    tagline: 'A four-bedroom terrace duplex wrapped in jasmine and set minutes from the beach.',
    description: 'Jasmine Court sits on a leafy, gated close off Admiralty Way, steps from the Atlantic shoreline. The duplex offers flexible family living — a downstairs guest suite, an open-plan kitchen and living floor, and four generously proportioned bedrooms upstairs, each opening onto a planted balcony.',
    features: [
      'Gated, landscaped close with guardhouse',
      'Open-plan kitchen and dining floor',
      'Guest suite on the ground floor',
      'Planted balconies on every bedroom',
      'Proximity to Lekki beach and schools',
      'Borehole water with treatment plant',
      'Solar-assisted power with battery backup',
      'Serviced by a dedicated estate management team',
    ],
    agent: {
      name: 'Chioma Eze',
      role: 'Sales Partner',
      phone: '+234 809 222 1076',
      email: 'chioma.eze@verdantestates.ng',
    },
  },
  {
    id: 4,
    name: 'Palm Boulevard Penthouse',
    type: 'Penthouse',
    price: 780000000,
    address: 'Bishop Oluwole Street, Victoria Island, Lagos',
    beds: 4,
    baths: 4,
    area: 380,
    yearBuilt: 2022,
    image: '/images/properties/property-4.jpg',
    tagline: 'A full-floor penthouse above Victoria Island with a wraparound sky terrace.',
    description: 'Occupying the entire 18th floor of a boutique tower on Victoria Island, Palm Boulevard Penthouse is a study in calm. Every room looks out over the city and the lagoon, and the wraparound terrace turns sunset hours into an event. The chef\'s kitchen, walk-in dressing rooms and spa bathroom complete the picture.',
    features: [
      'Full-floor footprint with private lift lobby',
      'Wraparound sky terrace with city views',
      'Chef\'s kitchen with integrated appliances',
      'Walk-in dressing rooms in all bedrooms',
      'Residents\' gym, pool and concierge',
      'Dedicated parking for four vehicles',
      'Tower-wide backup power and fibre internet',
      'Prime position near banks, hotels and schools',
    ],
    agent: {
      name: 'Femi Adeyemi',
      role: 'Luxury Resale Manager',
      phone: '+234 805 111 0834',
      email: 'femi.adeyemi@verdantestates.ng',
    },
  },
  {
    id: 5,
    name: 'Fern House',
    type: 'Semi-Detached Duplex',
    price: 460000000,
    address: '26 Ademola Adetokunbo Street, Oniru, Lagos',
    beds: 4,
    baths: 4,
    area: 360,
    yearBuilt: 2020,
    image: '/images/properties/property-5.jpg',
    tagline: 'A light-filled semi-detached duplex in Oniru with a fern-lined courtyard.',
    description: 'Fern House is built around a sunken courtyard that draws light and air deep into the plan. Oniru\'s newest quarter is walkable to Landmark beach and the city\'s best restaurants, yet the house feels a world away — green walls, timber screens and a quiet reading nook beneath the stairwell.',
    features: [
      'Sunken courtyard with water feature',
      'Green wall and passive cooling design',
      'Walkable to Landmark Beach',
      'Study nook with library shelving',
      'Ensuite bedrooms with rainfall showers',
      'Gated street with CCTV and security',
      'Efficient inverter and solar-ready wiring',
      'Low-maintenance native landscaping',
    ],
    agent: {
      name: 'Ngozi Obi',
      role: 'Sales Partner',
      phone: '+234 806 666 0912',
      email: 'ngozi.obi@verdantestates.ng',
    },
  },
  {
    id: 6,
    name: 'Cedar Villa',
    type: 'Detached Villa',
    price: 690000000,
    address: '12 Chevron Drive, Lekki, Lagos',
    beds: 5,
    baths: 6,
    area: 560,
    yearBuilt: 2021,
    image: '/images/properties/property-6.jpg',
    tagline: 'A five-bedroom villa off Chevron Drive with cedar ceilings and a forest garden.',
    description: 'Cedar Villa\'s timber-lined ceilings and exposed stone walls give it the warmth of a mountain lodge set in the heart of Lekki. The forest garden is planted entirely with native species, and a covered lanai stretches across the rear of the house for year-round outdoor living.',
    features: [
      'Cedar ceilings and stone feature walls',
      'Native-species forest garden',
      'Covered lanai with built-in grill',
      'Dual master suites with dressing rooms',
      'Large family lounge and media room',
      'Guest house with private entrance',
      'Borehole, treatment plant and solar hybrid',
      'Quiet, gated cul-de-sac off Chevron Drive',
    ],
    agent: {
      name: 'Ibrahim Suleiman',
      role: 'Sales Partner',
      phone: '+234 807 777 0621',
      email: 'ibrahim.suleiman@verdantestates.ng',
    },
  },
  {
    id: 7,
    name: 'Osborne Sky Residence',
    type: 'Apartment',
    price: 410000000,
    address: 'Osborne Foreshore, Ikoyi, Lagos',
    beds: 3,
    baths: 4,
    area: 250,
    yearBuilt: 2023,
    image: '/images/properties/property-7.jpg',
    tagline: 'A three-bedroom residence on Osborne Foreshore with lagoon views from every room.',
    description: 'Set along the Osborne Foreshore promenade, this three-bedroom residence offers rare water views in one of Ikoyi\'s most established addresses. The open-plan living floor flows onto a glass balcony, while the master suite enjoys a corner aspect over the lagoon and the city beyond.',
    features: [
      'Lagoon-facing corner balcony',
      'Open-plan living and dining floor',
      'Master suite with corner water views',
      'Residents\' pool, gym and tennis court',
      '24-hour concierge and security',
      'Two dedicated parking bays',
      'Backup power and treated water supply',
      'Walking distance to Ikoyi Club 1938',
    ],
    agent: {
      name: 'Adaeze Okafor',
      role: 'Senior Sales Partner',
      phone: '+234 803 555 0142',
      email: 'adaeze.okafor@verdantestates.ng',
    },
  },
  {
    id: 8,
    name: 'Canopy Loft',
    type: 'Duplex Apartment',
    price: 185000000,
    address: '9 Herbert Macaulay Way, Yaba, Lagos',
    beds: 3,
    baths: 3,
    area: 210,
    yearBuilt: 2022,
    image: '/images/properties/property-8.jpg',
    tagline: 'A designer duplex loft in Yaba\'s creative quarter, minutes from the train line.',
    description: 'Canopy Loft brings gallery-style living to Yaba, with a double-height living volume, exposed concrete and warm timber underfoot. It sits in the heart of the creative district — a short walk from the Blue Line station, tech hubs and the weekend food markets.',
    features: [
      'Double-height living volume',
      'Exposed concrete and timber finishes',
      'Walk-in pantry and utility room',
      'Roof terrace for entertaining',
      'Walking distance to the Blue Line station',
      'Bike store and co-working lounge',
      'Estate-wide fibre broadband',
      'Solar-assisted common power',
    ],
    agent: {
      name: 'Chioma Eze',
      role: 'Sales Partner',
      phone: '+234 809 222 1076',
      email: 'chioma.eze@verdantestates.ng',
    },
  },
  {
    id: 9,
    name: 'Veranda House',
    type: 'Townhouse',
    price: 240000000,
    address: '18 Adeniran Ogunsanya, Surulere, Lagos',
    beds: 3,
    baths: 3,
    area: 240,
    yearBuilt: 2019,
    image: '/images/properties/property-9.jpg',
    tagline: 'A classic Surulere townhouse with a deep veranda and a courtyard garden.',
    description: 'Veranda House honours Surulere\'s genteel past — deep verandas, timber louvers and a courtyard garden that cools the whole house. Renovated to modern standards in 2019, it keeps its neighbourhood character while gaining a modern kitchen, ensuites and full backup power.',
    features: [
      'Deep veranda with timber louvers',
      'Courtyard garden with rain capture',
      'Modern kitchen with island seating',
      'Renovated ensuites and fittings',
      'Carport and secure gated entry',
      'Central to Surulere\'s markets and cinemas',
      'Inverter with solar-ready wiring',
      'Quiet, tree-lined street',
    ],
    agent: {
      name: 'Femi Adeyemi',
      role: 'Luxury Resale Manager',
      phone: '+234 805 111 0834',
      email: 'femi.adeyemi@verdantestates.ng',
    },
  },
  {
    id: 10,
    name: 'Moss & Stone House',
    type: 'Detached Bungalow',
    price: 350000000,
    address: '5 Addo Road, Ajah, Lagos',
    beds: 4,
    baths: 5,
    area: 330,
    yearBuilt: 2021,
    image: '/images/properties/property-10.jpg',
    tagline: 'A single-storey retreat in Ajah where moss walls meet stone floors.',
    description: 'Moss & Stone House is a modern bungalow designed for single-level living — wide doorways, a flowing plan and no wasted corridor. The living wing opens onto a shaded veranda and a lawn that melts into the surrounding greenery, making it a favourite for growing families.',
    features: [
      'Single-level accessible floor plan',
      'Shaded veranda across the full rear',
      'Garden room with green wall',
      'Wide doorways and low-threshold entries',
      'Ensuite bedrooms around a central lawn',
      'Kitchen with scullery and store',
      'Borehole and full backup power',
      'Gated, landscaped compound',
    ],
    agent: {
      name: 'Ngozi Obi',
      role: 'Sales Partner',
      phone: '+234 806 666 0912',
      email: 'ngozi.obi@verdantestates.ng',
    },
  },
  {
    id: 11,
    name: 'Garden Terrace',
    type: 'Terrace Duplex',
    price: 290000000,
    address: '3 Sasegbon Street, Ilupeju, Lagos',
    beds: 4,
    baths: 4,
    area: 280,
    yearBuilt: 2020,
    image: '/images/properties/property-11.jpg',
    tagline: 'A four-bedroom terrace duplex on a leafy Ilupeju street near the golf course.',
    description: 'Garden Terrace lines a quiet, tree-shaded street in Ilupeju, close to the golf course and the city\'s main airport routes. Every floor catches the breeze, with generous windows, an open family kitchen and a rooftop terrace that catches the evening sun.',
    features: [
      'Rooftop terrace with planted beds',
      'Open family kitchen and dining floor',
      'Close to Ilupeju golf course and airport roads',
      'Ensuite bedrooms with built-in wardrobes',
      'Service quarters and laundry room',
      'Secure, gated and well-lit street',
      'Backup power with inverter',
      'Managed estate amenities',
    ],
    agent: {
      name: 'Ibrahim Suleiman',
      role: 'Sales Partner',
      phone: '+234 807 777 0621',
      email: 'ibrahim.suleiman@verdantestates.ng',
    },
  },
  {
    id: 12,
    name: 'Atlantic View Apartment',
    type: 'Apartment',
    price: 320000000,
    address: 'Eko Atlantic, Victoria Island, Lagos',
    beds: 2,
    baths: 2,
    area: 160,
    yearBuilt: 2023,
    image: '/images/properties/property-12.jpg',
    tagline: 'A two-bedroom apartment on the Eko Atlantic waterfront with ocean-facing balcony.',
    description: 'Steps from the Atlantic Ocean and the Eko Atlantic promenade, this two-bedroom apartment delivers effortless city living. Floor-to-ceiling glazing opens onto an ocean-facing balcony, and residents enjoy the estate\'s parks, gyms and 24-hour security.',
    features: [
      'Ocean-facing balcony with sea views',
      'Floor-to-ceiling glazing throughout',
      'Open-plan kitchen with stone counters',
      'Estate parks, gym and retail promenade',
      '24-hour security and concierge',
      'Two parking bays and storage room',
      'District cooling and backup power',
      'Reclaimed-land, flood-protected development',
    ],
    agent: {
      name: 'Tunde Bakare',
      role: 'Private Office Director',
      phone: '+234 802 444 0198',
      email: 'tunde.bakare@verdantestates.ng',
    },
  },
]

const listingsFile = join(dataDir, 'listings.json')
writeFileSync(listingsFile, JSON.stringify(PROPERTIES, null, 2))
console.log(`✅ Seeded ${PROPERTIES.length} listings into ${listingsFile}`)

// Initialise empty files if they don't exist
const empty = (file) => {
  const filepath = join(dataDir, file)
  if (!existsSync(filepath)) {
    writeFileSync(filepath, '[]')
    console.log(`   Created empty ${file}`)
  }
}
empty('enquiries.json')
empty('users.json')
empty('savedHomes.json')

console.log('🌿 Database ready!')
